services:
  schedules:
    image: schedules
    build: .
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
  db:
    image: mysql:5.6
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
    expose:
      - "3306"
    volumes:
      - ./db:/docker-entrypoint-initdb.d
      - schedulesdb:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 3
volumes:
  schedulesdb:
