spring:
  profiles.active: local
  main:
    banner-mode: "off"
---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:mysql://db:3306/schedulesdb
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password:
    testOnBorrow: true